CREATE TABLE IF NOT EXISTS  STATE_MACHINE (
  id        IDENTITY PRIMARY KEY NOT NULL,
  code  VARCHAR(100) NOT NULL,
  name      VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS  State_Group (
  id        IDENTITY PRIMARY KEY NOT NULL,
  name      VARCHAR(100) NOT NULL,
  color     VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS  STATE (
  id        IDENTITY PRIMARY KEY NOT NULL,
  code      VARCHAR(50) NOT NULL,
  name      VARCHAR(100) NOT NULL,
  isStart BOOLEAN DEFAULT FALSE,
  isFinal BOOLEAN DEFAULT FALSE,
  isExclusiveGateway BOOLEAN DEFAULT FALSE,
  stateMachineId INTEGER,
   groupId INTEGER,
  FOREIGN KEY (stateMachineId) REFERENCES STATE_MACHINE (id) ON DELETE CASCADE,
   FOREIGN KEY (groupId) REFERENCES State_Group (id)
);

CREATE TABLE IF NOT EXISTS  TRANSITION (
  id        IDENTITY PRIMARY KEY NOT NULL,
  name      VARCHAR(50),
  code      VARCHAR(50),
  isDefault BOOLEAN DEFAULT FALSE,
  stateId INTEGER,
  targetId INTEGER,
  conditionScript      VARCHAR(2000),
  action VARCHAR(2000),
  FOREIGN KEY (stateId) REFERENCES STATE (id) ON DELETE CASCADE,
  FOREIGN KEY (targetId) REFERENCES STATE (id) ON DELETE CASCADE,

);

CREATE TABLE IF NOT EXISTS  STATE_MACHINE_INSTANCE (
  id        IDENTITY PRIMARY KEY NOT NULL,
  stateMachineId INTEGER NOT NULL,
  stateId INTEGER NOT NULL,
  created timestamp NOT NULL,
  changed timestamp,
  FOREIGN KEY (stateMachineId) REFERENCES STATE_MACHINE (id),
  FOREIGN KEY (stateId) REFERENCES STATE (id)
);