INSERT INTO JiraGender (ID, GENDER, ISCLASSIC) VALUES (1, 'WOMAN', 1);
INSERT INTO JiraGender (ID, GENDER, ISCLASSIC) VALUES (2, 'MAN', 1);
INSERT INTO JiraGender (ID, GENDER, ISCLASSIC) VALUES (3, 'FOO', 0);
INSERT INTO JiraGender (ID, GENDER, ISCLASSIC) VALUES (4, 'BAR', 0);