GRANT CREATE SESSION TO SYSTEM
GRANT CREATE PROCEDURE TO SYSTEM
GRANT CREATE TABLE TO SYSTEM
GRANT SELECT ANY TABLE TO SYSTEM
GRANT DROP ANY TABLE TO SYSTEM
GRANT DROP ANY VIEW TO SYSTEM
GRANT CREATE VIEW TO SYSTEM
GRANT ALTER ANY TRIGGER TO SYSTEM
GRANT ALTER ANY SEQUENCE TO SYSTEM
GRANT CREATE SEQUENCE TO SYSTEM
GRANT CREATE TRIGGER TO SYSTEM
ALTER USER SYSTEM quota unlimited on USERS