CREATE TABLE IF NOT EXISTS  {{StateMachine}} (
  id        SERIAL PRIMARY KEY NOT NULL,
  code  VARCHAR(100) NOT NULL,
  name      VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS  {{StateGroup}} (
  id        SERIAL PRIMARY KEY NOT NULL,
  name      VARCHAR(100) NOT NULL,
  color     VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS  {{STATE}} (
  id        SERIAL PRIMARY KEY NOT NULL,
  code      VARCHAR(50) NOT NULL,
  name      VARCHAR(100) NOT NULL,
  isStart BOOLEAN DEFAULT FALSE,
  isFinal BOOLEAN DEFAULT FALSE,
  stateMachineId INTEGER NOT NULL,
  groupId INTEGER,
  FOREIGN KEY (stateMachineId) REFERENCES {{StateMachine}} (id) ON DELETE CASCADE,
  FOREIGN KEY (groupId) REFERENCES {{StateGroup}} (id)
);

CREATE TABLE IF NOT EXISTS  {{TRANSITION}} (
  id        SERIAL PRIMARY KEY NOT NULL,
  name      VARCHAR(50),
  isDefault BOOLEAN DEFAULT FALSE,
  stateId INTEGER,
  targetId INTEGER,
  FOREIGN KEY (stateId) REFERENCES {{STATE}} (id) ON DELETE CASCADE,
  FOREIGN KEY (targetId) REFERENCES {{STATE}} (id) ON DELETE CASCADE
);

ALTER TABLE {{transition}} ADD COLUMN IF NOT EXISTS "code" VARCHAR(50);
ALTER TABLE {{transition}} ADD COLUMN IF NOT EXISTS "conditionscript" VARCHAR(2000);

ALTER TABLE {{state}} ADD COLUMN IF NOT EXISTS "isexclusivegateway" BOOLEAN DEFAULT FALSE;