{
  "view-to": "TimeSheet",
  "sql": ["SELECT *\n",
  "  FROM (SELECT rownum AS rn\n",
  "              ,tsh.id AS tsh_id\n",
  "              ,sdv.name AS sdv_name\n",
  "              ,tsp.str_id AS str_id\n",
  "              ,RTRIM(per.last_name || ' ' || per.name || ' ' || per.patronymic) AS per_fio\n",
  "              ,drc.short_name AS table_number\n",
  "              ,COALESCE(tsp.plan_time, 0) AS plan_hours\n",
  "              ,tsp.work_day AS work_day\n",
  "              ,(SELECT SUM(COALESCE(wts.confirmed_time, 0)) AS work_package_hours\n",
  "                  FROM hr_wpa_time_sheet wts\n",
  "                       JOIN hr_wpa_performer wpe ON wpe.id = wts.wpe_id\n",
  "                       JOIN hr_work_package wpa ON wpa.id = wpe.wpa_id\n",
  "                       JOIN sk_bot_state st ON wpa.ost_id = st.id\n",
  "                       LEFT JOIN hr_work_team_member wtm ON wtm.id = wpe.wtm_id\n",
  "                 WHERE     1 = 1\n",
  "                       AND st.state NOT IN ('001', '000')\n",
  "                       AND wts.work_day = tsp.work_day\n",
  "                       AND COALESCE(wpe.str_id, wtm.str_id) = str.id)\n",
  "                  AS work_package_hours\n",
  "              ,COALESCE\n",
  "               (\n",
  "                  (SELECT SUM(SUBSTR(COLUMN_VALUE,INSTR(COLUMN_VALUE,';',1,1), 1))\n",
  "                     FROM TABLE\n",
  "                          (CAST(ty_varchar2_list(tsp.apt_id_1 || ';' || tsp.confirmed_time_1\n",
  "                                                ,tsp.apt_id_2 || ';' || tsp.confirmed_time_2\n",
  "                                                ,tsp.apt_id_3 || ';' || tsp.confirmed_time_3\n",
  "                                                ,tsp.apt_id_4 || ';' || tsp.confirmed_time_4\n",
  "                                                ,tsp.apt_id_5 || ';' || tsp.confirmed_time_5) AS ty_varchar2_list\n",
  "                             )\n",
  "                          )\n",
  "                    WHERE 1 = 1\n",
  "                          AND SUBSTR(COLUMN_VALUE,1,INSTR(COLUMN_VALUE,';',1,1)- 1) IN\n",
  "                                 (SELECT agd.apt_id\n",
  "                                    FROM    sk_apt_group_detail agd\n",
  "                                         JOIN sk_appearance_type_group atg ON atg.id = agd.atg_id\n",
  "                                   WHERE atg.code IN ('СВЕРХУРОЧНЫЕ', 'УРОЧНОЕ_ВРЕМЯ')))\n",
  "                 ,0)\n",
  "                  AS worked_hours\n",
  "          FROM hr_time_sheet tsh\n",
  "               JOIN hr_time_sheet_position tsp ON tsp.tsh_id = tsh.id\n",
  "               JOIN hr_labour_pact lp ON lp.id = tsp.lpa_id\n",
  "               JOIN hr_staff_unit_profession sup ON sup.id = lp.sup_id\n",
  "               JOIN hr_staff_unit su ON su.id = sup.stu_id\n",
  "               JOIN sk_subdivision sdv ON su.subdivision_drc_value = sdv.subdivision_drc_value\n",
  "               JOIN hr_staff_record str ON str.id = tsp.str_id\n",
  "               JOIN hr_employee emp ON emp.id = str.emp_id\n",
  "               JOIN hr_person per ON per.id = emp.per_id\n",
  "               LEFT JOIN sk_dictionary_record_t drc ON str.table_number_drc_id = drc.id\n",
  "               ORDER BY table_number, work_day)\n",
  " WHERE work_package_hours > 0"],
  //маппим колонки селекта на нашу сущность.
  //если какая то колонка не упомянута в мапингах - она летит в датамапу как есть
  "mappings": {
    "id": "rn",
    //из трех выбранных полей мы слепим вложенный объект и скажем что это Employee
    "employee": {
      "alias-of": "Employee",
      "fields":"per_id,per_fio,table_number"
      }
    }
  }